### ISSUE TITLE
NoClassDefFoundError Exception in UserIdentity

### ISSUE THREAD

**Issue by fkoepke** [Yubico/java-webauthn-server#63]
I have the following code to start the registration:
```
byte[] userIdByteArray = Longs.toByteArray(userId);

    PublicKeyCredentialCreationOptions credentialCreation = this.relyingParty
        .startRegistration(
            StartRegistrationOptions
                .builder()
                .user(
                    UserIdentity
                        .builder()
                        .name(name)
                        .displayName(displayName)
                        .id(
                            new ByteArray(userIdByteArray)
                        )
                        .build()
                )
                .build());
```
With the debugger I get in credentialCreation in the line with `UserIdentity.builder().id()`: `Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate com.yubico.webauthn.data.UserIdentity.toString()`.

For the challenge in credentialCreation I get in the debugger the same error `Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate com.yubico.webauthn.data.ByteArray.toString()`.

Maybe there is something wrong in my code but I can't see any differences in the documentation.

**Comment by imfede** [comment]
add [this](https://search.maven.org/artifact/com.yubico/yubico-util/1.6.1/jar) to your dependencies. I think it's the same problem I am facing (#64)

**Comment by imfede** [comment]
also this should be same underlying issue as of #62, see if using version `1.6.1` solves your issue

**Comment by fkoepke** [comment]
I have this in my pom.xml:
```
<dependency>
	<groupId>com.yubico</groupId>
	<artifactId>yubico-util</artifactId>
	<version>1.6.1</version>
</dependency>

<dependency>
	<groupId>com.yubico</groupId>
	<artifactId>webauthn-server-core</artifactId>
	<version>1.6.1</version>
	<scope>compile</scope>
</dependency>
```

**Comment by imfede** [comment]
sorry I typed the wrong version number. try only this
```xml
<dependency>
	<groupId>com.yubico</groupId>
	<artifactId>webauthn-server-core</artifactId>
	<version>1.6.0</version>
</dependency>
```
it should import all the necessary dependencies on its own

**Comment by fkoepke** [comment]
Thanks @imfede, it works with version 1.6.0.

**Comment by emlun** [comment]
Sorry, dependency declarations are missing in the 1.6.1 release. Release 1.6.2 fixes this - `yubico-util` should not be needed as a direct dependency.

Duplicate of #62.
